# Configs

title: "Zarin Fabiha"
name: "Jekyll website for Zarin Fabiha"
email: z2019125@student.niu.edu
url: "https://z2019125.github.io
baseurl: "/Zarin-Fabiha-Websites"
repository: "z2019125/Zarin-Fabiha-Websites"
header:
  image: /assets/images/"C:\Users\Z2019125\Desktop\IMG_5794.HEIC"

include:
  - _pages
  - assets
  - index.html
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "contrast"

# settings for author profile
author:
  name   : "Zarin Fabiha"
  avatar : "/assets/images/"C:\Users\Z2019125\Desktop\IMG_5794.HEIC"

  bio    : "My name is Zarin Fabiha, and I am a student at Northern Illinois University."
  location: "DeKalb, Illinois"
  github : 
  linkedin: zareen-fabiha-aa6008336/
  email  : z2019125@student.niu.edu


# # comments by disqus
#comments:
  #provider: "disqus"
  #disqus:
    #shortname: "pwills-com"

#analytics:
  #provider: "google"
  #google:
    #tracking_id: "UA-116208936-1"


# pagination for blog page
paginate: 10 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: false
      comments: true
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

# collections
collections:
  portfolio:
    output: true
